version: "3"
services:
    web:
        container_name: notion-meeting-app
        build:
            context: ./golang
            target: DEV
        ports:
            - 8080:8080
        volumes:
            - ./golang:/go/src/app
        tty: true
        depends_on:
            - db
    db:
        container_name: notion-meeting-app-db
        build: ./postgres
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: notion-meeting-app
        ports:
            - 5432:5432
        tty: true