version: "3"
services:
    web:
        container_name: notion-meeting-app
        build: ./golang
        ports:
            - 8080:8080
        volumes:
            - ./golang:/go/src/app
        tty: true
        depends_on:
            - db
    db:
        container_name: notion-meeting-app-db
        build: ./postgres
        env_file: ./.env
        environment:
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD
            POSTGRES_USER: $POSTGRES_USER
            POSTGRES_DB: $POSTGRES_DB
        ports:
            - 5432:5432
        tty: true